apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clustersecrets.clustersecret.io
spec:
  scope: Namespaced
  group: clustersecret.io
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: ClusterSecret
    plural: clustersecrets
    singular: clustersecret
    shortNames:
      - csec